export function getLocalizedUi(locale) {
  return withLocaleOverrides(getUi(locale), locale);
}

const ZH_UI_OVERRIDES = {
  appTitle: "PineFlow 桌面端",
  health: { label: "服务", ready: "GIS 引擎已就绪", checking: "正在检查 API", pyqgisReady: "PyQGIS 可用", apiReachable: "API 可访问" },
  actions: {
    settings: "设置",
    reset: "重置会话",
    addFiles: "添加文件",
    clear: "清空",
    collapseLeft: "收起左栏",
    expandLeft: "展开左栏",
    collapseRight: "收起详情栏",
    expandRight: "展开详情栏",
    remove: "移除",
    delete: "删除",
    cancel: "取消",
    pause: "暂停",
    cancelRun: "取消运行",
    send: "发送",
    search: "搜索",
    copy: "复制路径",
    choose: "选择",
    view: "查看",
    open: "打开",
    save: "保存",
    waiting: "等待中",
    submitPatch: "提交参数",
    replan: "重新规划",
  },
  sections: { dataSources: "数据源", conversation: "对话", workflow: "处理详情", settings: "设置", errors: "错误" },
  tabs: { state: "图层", outputs: "结果", decisions: "审查", evidence: "方法视图", memory: "备注" },
  session: { noSession: "暂无会话" },
  sessionNav: {
    title: "会话",
    newSession: "新建会话",
    collapseNav: "收起会话栏",
    expandNav: "展开会话栏",
    archive: "归档",
    deleteSession: "删除会话",
    confirmArchive: "确定归档此会话？归档只会移出当前列表，不会删除导出文件。",
    confirmDelete: "确定删除此会话？会话记录和临时处理文件将移到回收站，不会删除 data 目录里的导出结果。",
  },
  memory: {
    title: "会话备注",
    placeholder: "记录任务背景、已确认信息和后续要注意的内容...",
    saved: "已保存",
    saveFailed: "保存失败",
    edit: "编辑",
    saveMemory: "保存备注",
  },
  workflow: {
    title: "处理过程",
    ready: "等待执行。",
    preparing: "正在准备工作流...",
    thinking: "正在思考",
    thinkingHint: "正在理解任务、检查当前会话状态并准备下一步操作。",
    thinkingSteps: ["理解任务", "检查图层状态", "选择工具"],
    noPlan: "暂无流程事件。",
    stepFallback: "工具调用 {index}",
    stepStart: "调用开始",
    callStarted: "第 {index} 次调用：{detail}",
    waitingStep: "等待该步骤开始。",
    thought: "判断",
    action: "处理操作",
    processingLog: "过程记录",
    technicalDetails: "详细信息",
    debugDetails: "调试详情",
    tool: "工具",
    toolId: "Tool ID",
    input: "输入",
    artifact: "结果",
    parameters: "参数",
    observation: "处理结果",
    output: "输出",
    outputFile: "输出文件",
    outputLayer: "结果图层",
    resultMetadata: "结果信息",
    warning: "数据质量提示",
    repair: "自动修复",
    toolkit_selection: "工具包",
    retry: "重试",
    question: "需要输入",
    confirmation: "等待确认",
    error: "错误",
    temporaryResult: "临时结果",
    preparedAction: "准备执行：",
    statuses: { pending: "待执行", current: "运行中", running: "运行中", done: "完成", completed: "完成", awaiting: "需输入", awaiting_user: "需输入", error: "失败", failed: "失败", warning: "需留意" },
    actionLabels: {
      select_toolkit: "准备工具能力",
      inspect_workspace: "检查工作区",
      load_skill: "加载 GIS 知识",
      load_vector: "加载矢量图层",
      load_raster: "加载栅格图层",
      csv_to_points: "CSV 转点图层",
      reproject_layer: "重投影图层",
      fix_geometries: "修复几何",
      delete_duplicate_geometries: "删除重复几何",
      snap_geometries: "几何捕捉",
      check_validity: "检查几何有效性",
      buffer_layer: "缓冲区分析",
      clip_layer: "裁剪分析",
      extract_by_attribute: "按属性筛选",
      extract_by_location: "按位置筛选",
      join_by_location: "空间连接",
      field_calculator: "字段计算",
      raster_calculator: "栅格计算",
      zonal_statistics: "分区统计",
      terrain_ruggedness_index: "地形起伏指数",
      topographic_position_index: "地形位置指数",
      roughness: "地形粗糙度",
      export_result: "导出结果",
      run_algorithm: "运行处理算法",
      "native:buffer": "缓冲区分析",
      "native:clip": "裁剪分析",
      "native:fixgeometries": "几何修复",
    },
  },
  empty: { noFilesSelected: "尚未选择文件。", noStateTree: "暂无状态树图层。", noOutputs: "暂无输出结果。" },
  messages: { taskCompleted: "任务已完成。", taskFailed: "任务失败。", missingParameter: "还需要补充参数。" },
  narrative: {
    runLabel: "处理",
    runStart: "开始处理",
    done: "已完成",
    doing: "正在处理",
    resumeLabel: "继续",
    resumeTitle: "接着处理",
    completed: "处理完成",
    deliveryLabel: "结果",
    process: "处理过程",
  },
  errors: {
    filePickerDesktopOnly: "文件选择器仅在桌面端可用。",
    filePickerFailed: "打开文件选择器失败。",
    directoryPickerFailed: "选择目录失败。",
    fillPendingParams: "请先补齐待填参数。",
    singleSourceRequired: "当前待补数据只需要选择一个文件。",
    sourceTypeMismatch: "所选文件 {file} 不符合当前要求，请选择：{types}。",
    apiKeyRequired: "所选模型提供方需要 API Key。",
    baseUrlAndModelRequired: "请填写 LLM Base URL 和模型名称。",
    requestFailed: "请求失败。",
  },
  outputs: { outputFallback: "输出", reportTitle: "分析报告", dataTitle: "数据结果", reportFallback: "最终报告" },
  decisions: {
    empty: "暂无需要留意的记录。",
    clarificationTitle: "主动澄清",
    userResolutionTitle: "用户处理",
    riskDecisionTitle: "风险确认",
    runtimeRiskTitle: "运行提示",
    repairTitle: "修复记录",
    exportTitle: "导出记录",
    emptyResultTitle: "空结果诊断",
    qualityTitle: "结果提示",
    goalSource: "目标来源",
    assumptions: "已确认前提",
    intent: "意图",
    choice: "用户选择",
    slotPatch: "参数变更",
    decision: "处理方式",
    affectsTrust: "可能影响结果",
    blocking: "阻断",
    code: "代码",
    affectedArtifacts: "影响产物",
    action: "操作",
    layer: "图层",
    reason: "依据",
    inputLayer: "输入图层",
    outputLayer: "输出图层",
    featureChange: "要素数变化",
  },
  evidence: {
    kicker: "Method View",
    tab: "方法视图",
    title: "论文方法展示面板",
    subtitle: "只读展示当前运行中的结构化行动计划、工作区状态、校验记录和执行观察。",
    copy: "复制机制数据",
    copied: "已复制",
    copyTitle: "复制当前方法视图 JSON",
    actionPlan: "ActionPlan 映射",
    actionPlanNote: "论文抽象 A={s,a,p} 对应代码字段 thought/action/action_input。",
    noActionPlan: "当前快照未记录可展示的 ActionPlan。",
    notRecorded: "未记录",
    workspace: "工作区状态",
    workspaceNote: "来自 state_tree layers 与 artifact outputs。",
    layers: "图层",
    artifacts: "产物",
    layerFallback: "图层",
    artifactFallback: "产物",
    role: "角色",
    lineage: "来源关系",
    outputPath: "输出路径",
    artifactDetails: "查看 artifact 写回详情",
    noWorkspace: "当前快照暂无工作区图层。",
    skills: "领域知识指导",
    skillNote: "skill 是认知指导，不直接执行 GIS 工具，也不作为执行许可。",
    skillFallback: "skill",
    noSkills: "当前快照未记录显式 suggest_skill/load_skill；未持久化的自动提示不会在此伪造。",
    sourceField: "来源",
    summary: "摘要",
    validation: "规则校验",
    validationNote: "展示已记录的 issues、risks、pending_task 和 warnings；不伪造完整 pass 清单。",
    validationItem: "校验记录",
    kind: "类型",
    severity: "级别",
    message: "消息",
    noValidationItems: "当前快照未记录阻断 issue/warning；系统未持久化完整 pass 清单。",
    observation: "执行观察与写回",
    observationNote: "来自最近 Observation、output_artifact、state_tree 或 artifact 事件。",
    observationFallback: "最近执行观察",
    writeback: "写回状态",
    writebackYes: "已在工作区或 artifact 中找到对应结果",
    writebackUnknown: "当前快照未确认写回记录",
    observationJson: "Observation JSON",
    noObservation: "当前快照暂无 Observation。",
    rawEvidence: "原始运行数据 JSON",
    rawNote: "用于截图之外的核验，默认折叠。",
    expandJson: "展开 JSON",
  },
  diagnosis: {
    possibleCauses: "可能原因",
    nextActions: "建议下一步",
    actions: {
      keep_empty_result: "保留空结果",
      modify_filter: "修改筛选条件",
      inspect_fields: "查看字段取值",
      check_crs: "检查图层坐标系",
      reproject_inputs: "先统一坐标系",
      inspect_extents: "检查图层范围",
      inspect_inputs: "检查输入图层",
      change_spatial_relation: "调整空间关系或叠加图层",
      backtrack_previous_step: "回退到上一步",
    },
    phrases: {
      "One or more input layers already contain 0 features.": "一个或多个输入图层本身没有要素。",
      "Input layers use different CRS values.": "输入图层使用了不同坐标系。",
      "Input layer extents do not appear to overlap.": "输入图层的空间范围可能没有重叠。",
      "The attribute filter may not match any records.": "属性筛选条件可能没有匹配任何记录。",
      "Raster band metadata is missing.": "栅格波段信息缺失。",
      "Raster extent metadata is missing.": "栅格范围信息缺失。",
      "The tool ran successfully, but no output records were produced.": "工具执行成功，但没有生成可用记录。",
      "Check the input layer before rerunning the analysis.": "重新分析前先检查输入图层。",
      "Reproject layers to a shared CRS before spatial overlay or extraction.": "空间叠加或筛选前，先把图层统一到同一坐标系。",
      "Inspect layer extents and CRS alignment.": "检查图层范围和坐标系是否对齐。",
      "Inspect field values or loosen the filter condition.": "查看字段取值，或放宽筛选条件。",
      "Check raster band, extent, NoData, and resolution settings.": "检查栅格波段、范围、NoData 和分辨率设置。",
      "Review CRS, spatial predicates, filters, and input data coverage.": "检查坐标系、空间关系、筛选条件和输入数据覆盖范围。",
    },
  },
  state: { layerFallback: "图层 {index}" },
  layers: { crs: "坐标系", geometry: "几何", features: "要素", fields: "字段", source: "来源" },
  common: { auto: "自动" },
  composer: {
    placeholder: "描述一个 GIS 任务，例如：给道路缓冲 200 米并裁剪到行政区边界。",
    quickActions: "快捷查看",
    autoReview: "自动审查",
    commandHint: "输入 / 选择命令",
    confirmReset: "确定清空当前会话上下文吗？",
    fields: "字段",
    fieldsDesc: "查看当前图层字段",
    layers: "图层",
    layersDesc: "查看已加载图层",
    crs: "坐标系",
    crsDesc: "查看图层 CRS",
    outputs: "结果",
    outputsDesc: "查看输出文件",
    last: "上一步",
    lastDesc: "查看最近成功步骤",
    reset: "重置",
    resetDesc: "清空当前会话上下文",
  },
  resume: {
    reviewNeeded: "需要确认",
    inputNeeded: "需要补充",
    confirmationTitle: "需要确认",
    pendingTask: "待处理任务",
    waiting: "等待你的下一步操作。",
    operationFallback: "当前操作",
    operationSentence: "{operation}这一步卡住了。",
    filledSlots: "已填参数",
    noFilled: "暂无已填参数",
    missingSlots: "缺失参数",
    noMissing: "暂无缺失参数",
    repairSentence: "建议先{repair}。",
    repairSentenceWithReason: "建议先{repair}。{reason}",
    continueSentence: "处理完后，继续{continueWith}。",
    applyRepair: "建议先处理后继续。",
    riskTitle: "GIS 风险",
    riskCategory: "风险类型",
    riskFallback: "风险",
    affectsTrust: "这个问题可能影响结果。",
    suggestedChoices: "候选项",
    selectChoice: "使用",
    selectChoiceMessage: "选择候选项：{choice}",
    sourceRequestsTitle: "需要文件",
    sourceRequiredHint: "当前任务需要先补充数据文件。",
    attachSourceAndContinue: "补充文件并继续",
    useSourcePanelHint: "请在左侧选择文件后继续。",
    sourceAttachedMessage: "已补充 {slot} 所需数据：{files}。接着处理。",
    sourceTypeFallback: "数据文件",
    sourceTypes: {
      vector: "矢量",
      raster: "栅格",
      csv: "CSV",
    },
    fillParameters: "填写后继续",
    changeTask: "修改任务",
    confirmRepair: "继续",
    reject: "跳过",
    cancelTask: "取消任务",
    patchHint: "填写后继续。",
    repairActionFallback: "修复动作",
    confirmRepairMessage: "确认应用建议修复。",
    rejectRepairMessage: "拒绝建议修复。",
    cancelTaskMessage: "取消当前待处理 GIS 任务。",
    patchSummary: "补充待处理任务参数：{patch}",
    repairActions: {
      reproject_layer: "重投影图层",
      fix_geometries: "修复几何",
      run_algorithm: "运行处理算法",
      load_vector: "加载矢量图层",
      load_raster: "加载栅格图层",
    },
    riskCategories: {
      crs_risk: "坐标系风险",
      geometry_risk: "几何风险",
      field_risk: "字段风险",
      layer_ambiguity: "图层歧义",
      output_risk: "输出风险",
      empty_result_risk: "空结果风险",
      raster_risk: "栅格风险",
      data_quality_risk: "数据质量风险",
      runtime_repair_risk: "运行修复风险",
    },
  },
  settings: {
    apiBaseUrl: "API 地址",
    provider: "提供方",
    providers: { deepseek: "DeepSeek", qwen: "通义千问", glm: "智谱GLM", openaiCompatible: "OpenAI / 兼容接口" },
    apiKey: "API Key",
    llmBaseUrl: "LLM Base URL",
    model: "模型",
    qgisLauncher: "QGIS 启动器",
    qgisPrefixPath: "QGIS Prefix Path",
    language: "语言",
    languages: { zh: "中文", en: "英文" },
    outputDirectory: "输出目录",
    chooseDirectory: "选择目录",
    outputFormat: "输出格式",
    llmMaxTokens: "最大输出 Tokens",
    llmTopP: "Top P",
    llmJsonMode: "JSON 响应模式",
  },
  statuses: { idle: "空闲", running: "运行中", pause_requested: "正在暂停", paused: "已暂停", cancel_requested: "正在取消", cancelled: "已取消", awaiting_user: "等待用户", awaiting_confirmation: "等待确认", completed: "完成", failed: "失败", checking: "检查中", online: "在线", offline: "离线", error: "错误" },
  slots: { input_ref: "输入图层", overlay_ref: "叠加图层", distance: "距离", input_refs: "输入图层", target_crs: "目标 CRS", field: "字段", field_name: "字段名", operator: "运算符", value: "值", predicate: "空间关系", intersect_ref: "相交图层", join_ref: "连接图层", formula: "公式", x_field: "X 字段", y_field: "Y 字段", layer_ref: "图层", mask_ref: "掩膜图层", raster_ref: "栅格图层", output_dir: "输出目录", output_format: "输出格式", output_name: "文件名" },
};

function withLocaleOverrides(ui, locale) {
  if (locale !== "zh-CN") return ui;
  return mergeUi(ui, ZH_UI_OVERRIDES);
}

function mergeUi(base, overrides) {
  const result = { ...base };
  for (const [key, value] of Object.entries(overrides || {})) {
    if (value && typeof value === "object" && !Array.isArray(value)) {
      result[key] = mergeUi(result[key] && typeof result[key] === "object" ? result[key] : {}, value);
    } else { result[key] = value; }
  }
  return result;
}

function getUi(locale) {
  void locale;
  return {
    appTitle: "PineFlow Desktop",
    health: { label: "Service", ready: "GIS engine ready", checking: "Checking API", pyqgisReady: "PyQGIS ready", apiReachable: "API reachable" },
    actions: {
      settings: "Settings", reset: "Reset Session", addFiles: "Add Files", clear: "Clear",
      collapseLeft: "Collapse Left Panel", expandLeft: "Expand Left Panel",
      collapseRight: "Collapse Details", expandRight: "Expand Details",
      remove: "Remove", delete: "Delete", cancel: "Cancel", pause: "Pause", send: "Send", search: "Search",
      cancelRun: "Cancel Run",
      copy: "Copy Path", choose: "Choose", view: "View", open: "Open", save: "Save",
      waiting: "Waiting", submitPatch: "Submit Patch", replan: "Replan",
    },
    sections: { dataSources: "Data Sources", conversation: "Conversation", workflow: "Details", settings: "Settings", errors: "Issues" },
    tabs: { state: "Layers", outputs: "Results", decisions: "Review", evidence: "Method View", memory: "Notes" },
    session: { noSession: "No session" },
    sessionNav: {
      title: "Sessions", newSession: "New Session",
      collapseNav: "Collapse session list", expandNav: "Expand session list",
      archive: "Archive", deleteSession: "Delete Session",
      confirmArchive: "Archive this session? This only removes it from the active list and keeps exported files.",
      confirmDelete: "Delete this session? Session records and temporary files will move to trash. Exported files under data are kept.",
    },
    memory: {
      title: "Session Notes", placeholder: "Keep background, confirmed details, and anything worth remembering...",
      saved: "Saved", saveFailed: "Save failed", edit: "Edit", saveMemory: "Save Notes",
    },
    workflow: {
      title: "Process", ready: "Waiting for analysis.", preparing: "Preparing analysis...",
      noPlan: "No analysis activity yet.", stepFallback: "Analysis operation {index}",
      stepStart: "Operation started", callStarted: "Operation {index}: {detail}",
      waitingStep: "Waiting for this operation to start.",
      thought: "Reasoning", action: "Operation", processingLog: "Process log",
      technicalDetails: "Details", debugDetails: "Debug details", tool: "Tool", toolId: "Tool ID", input: "Input", artifact: "Result", parameters: "Parameters",
      observation: "Processing result", output: "Output", warning: "Data quality note",
      outputFile: "Output file", outputLayer: "Output layer", resultMetadata: "Result details",
      repair: "Repair", toolkit_selection: "Capabilities", retry: "Retry",
      question: "Input needed", confirmation: "Waiting for confirmation", error: "Error",
      temporaryResult: "Temporary result", preparedAction: "Preparing: ",
      statuses: { pending: "Pending", current: "Running", running: "Running", done: "Done", completed: "Done", awaiting: "Input needed", awaiting_user: "Input needed", error: "Failed", failed: "Failed", warning: "Review" },
      actionLabels: {
        select_toolkit: "Prepare tools", inspect_workspace: "Inspect workspace", load_skill: "Load GIS guidance",
        load_vector: "Load vector layer", load_raster: "Load raster layer", csv_to_points: "Convert CSV to points",
      reproject_layer: "Reproject layer", fix_geometries: "Fix geometries", buffer_layer: "Buffer analysis",
        delete_duplicate_geometries: "Delete duplicate geometries", snap_geometries: "Snap geometries", check_validity: "Check geometry validity",
        clip_layer: "Clip analysis", extract_by_attribute: "Attribute filter", extract_by_location: "Location filter",
        join_by_location: "Spatial join", field_calculator: "Field calculation", raster_calculator: "Raster calculation",
        zonal_statistics: "Zonal statistics", terrain_ruggedness_index: "Terrain ruggedness index",
        topographic_position_index: "Topographic position index", roughness: "Roughness",
        export_result: "Export result", run_algorithm: "Run processing algorithm",
        "native:buffer": "Buffer analysis", "native:clip": "Clip analysis", "native:fixgeometries": "Geometry repair",
      },
    },
    empty: { noFilesSelected: "No files selected yet.", noStateTree: "No state tree layers available.", noOutputs: "No outputs available." },
    messages: { taskCompleted: "Task completed.", taskFailed: "Task failed.", missingParameter: "More parameters are needed." },
    narrative: {
      runLabel: "Processing",
      runStart: "Starting",
      done: "Done",
      doing: "Working",
      resumeLabel: "Continue",
      resumeTitle: "Continue",
      completed: "Finished",
      deliveryLabel: "Result",
      process: "Steps",
    },
    errors: {
      filePickerDesktopOnly: "The file picker is available only in the desktop app.",
      filePickerFailed: "Failed to open the file picker.", directoryPickerFailed: "Failed to choose directory.",
      fillPendingParams: "Fill in the pending parameters first.", singleSourceRequired: "Only one file is needed for this pending data request.",
      sourceTypeMismatch: "Selected file {file} does not match the required type. Choose: {types}.", apiKeyRequired: "An API key is required for the selected provider.",
      baseUrlAndModelRequired: "Fill in the LLM base URL and model.", requestFailed: "Request failed.",
    },
    outputs: { outputFallback: "output", reportTitle: "Analysis report", dataTitle: "Data results", reportFallback: "Final report" },
    decisions: {
      empty: "No notable items yet.",
      clarificationTitle: "Clarification",
      userResolutionTitle: "User resolution",
      riskDecisionTitle: "Risk decision",
      runtimeRiskTitle: "Runtime note",
      repairTitle: "Repair note",
      exportTitle: "Export note",
      emptyResultTitle: "Empty result diagnosis",
      qualityTitle: "Result note",
      goalSource: "Goal source",
      assumptions: "Confirmed assumptions",
      intent: "Intent",
      choice: "Choice",
      slotPatch: "Slot patch",
      decision: "Handling",
      affectsTrust: "May affect result",
      blocking: "Blocking",
      code: "Code",
      affectedArtifacts: "Affected artifacts",
      action: "Action",
      layer: "Layer",
      reason: "Reason",
      inputLayer: "Input layer",
      outputLayer: "Output layer",
      featureChange: "Feature count",
    },
    evidence: {
      kicker: "Method View",
      tab: "Method View",
      title: "Thesis Method View",
      subtitle: "Read-only view of structured action plans, workspace state, validation records, and execution observations.",
      copy: "Copy method data",
      copied: "Copied",
      copyTitle: "Copy current method-view JSON",
      actionPlan: "ActionPlan mapping",
      actionPlanNote: "Thesis abstraction A={s,a,p} maps to thought/action/action_input.",
      noActionPlan: "No ActionPlan is recorded in the current snapshot.",
      notRecorded: "Not recorded",
      workspace: "Workspace state",
      workspaceNote: "Derived from state_tree layers and artifact outputs.",
      layers: "layers",
      artifacts: "artifacts",
      layerFallback: "Layer",
      artifactFallback: "Artifact",
      role: "Role",
      lineage: "Lineage",
      outputPath: "Output path",
      artifactDetails: "Show artifact write-back details",
      noWorkspace: "No workspace layers are recorded in this snapshot.",
      skills: "Domain guidance",
      skillNote: "Skills are cognitive guidance; they do not execute GIS tools or grant execution permission.",
      skillFallback: "skill",
      noSkills: "No explicit suggest_skill/load_skill record is present; unsaved automatic hints are not fabricated here.",
      sourceField: "Source",
      summary: "Summary",
      validation: "Validation",
      validationNote: "Shows recorded issues, risks, pending_task, and warnings; it does not fabricate a full pass checklist.",
      validationItem: "Validation item",
      kind: "Kind",
      severity: "Severity",
      message: "Message",
      noValidationItems: "No blocking issue/warning is recorded; complete pass checklists are not persisted.",
      observation: "Observation and write-back",
      observationNote: "Derived from the latest Observation, output_artifact, state_tree, or artifact event.",
      observationFallback: "Latest observation",
      writeback: "Write-back",
      writebackYes: "Matching result found in workspace or artifact state",
      writebackUnknown: "No confirmed write-back record in the current snapshot",
      observationJson: "Observation JSON",
      noObservation: "No Observation is recorded in this snapshot.",
      rawEvidence: "Raw runtime data JSON",
      rawNote: "For verification outside screenshots; collapsed by default.",
      expandJson: "Expand JSON",
    },
    diagnosis: {
      possibleCauses: "Possible causes",
      nextActions: "Suggested next steps",
      actions: {
        keep_empty_result: "Keep empty result",
        modify_filter: "Modify filter",
        inspect_fields: "Inspect field values",
        check_crs: "Check layer CRS",
        reproject_inputs: "Reproject inputs",
        inspect_extents: "Inspect extents",
        inspect_inputs: "Inspect input layers",
        change_spatial_relation: "Change spatial relation or overlay",
        backtrack_previous_step: "Go back to previous step",
      },
      phrases: {},
    },
    state: { layerFallback: "layer {index}" },
    layers: { crs: "CRS", geometry: "Geometry", features: "Features", fields: "Fields", source: "Source" },
    common: { auto: "auto" },
    composer: {
      placeholder: "Describe a GIS task, for example: buffer roads by 200 meters and clip to the district boundary.",
      quickActions: "Quick lookups", commandHint: "Type / to choose a command",
      autoReview: "Auto review",
      confirmReset: "Clear the current session context?",
      fields: "Fields", fieldsDesc: "Show current layer fields",
      layers: "Layers", layersDesc: "Show loaded layers",
      crs: "CRS", crsDesc: "Show layer CRS",
      outputs: "Results", outputsDesc: "Show output files",
      last: "Last step", lastDesc: "Show the latest successful step",
      reset: "Reset", resetDesc: "Clear session context",
    },
    resume: {
      reviewNeeded: "Confirmation needed", inputNeeded: "More input needed",
      confirmationTitle: "Need confirmation",
      pendingTask: "Pending task", waiting: "Waiting for your next action.",
      operationFallback: "Current operation",
      operationSentence: "The task is currently stuck at {operation}.",
      filledSlots: "Filled slots", noFilled: "No filled slots",
      missingSlots: "Missing slots", noMissing: "No missing slots",
      repairSentence: "Fix it with {repair} first.",
      repairSentenceWithReason: "Fix it with {repair} first. {reason}",
      continueSentence: "After that, continue with {continueWith}.",
      applyRepair: "Handle this first, then continue.",
      riskTitle: "GIS risk", riskCategory: "Risk type", riskFallback: "risk",
      affectsTrust: "This may affect the result.", suggestedChoices: "Suggested choices",
      selectChoice: "Use", selectChoiceMessage: "Use candidate: {choice}",
      sourceRequestsTitle: "Files needed",
      sourceRequiredHint: "This task needs additional data files first.",
      attachSourceAndContinue: "Attach file and continue",
      useSourcePanelHint: "Use the left panel to attach files, then continue.",
      sourceAttachedMessage: "Attached data for {slot}: {files}. Continue the task.",
      sourceTypeFallback: "data file",
      sourceTypes: {
        vector: "vector",
        raster: "raster",
        csv: "CSV",
      },
      fillParameters: "Fill and continue", changeTask: "Change task",
      confirmRepair: "Continue", reject: "Skip",
      cancelTask: "Cancel task", patchHint: "Fill in the missing values and continue.",
      repairActionFallback: "repair_action", confirmRepairMessage: "Confirm the suggested repair.",
      rejectRepairMessage: "Reject the suggested repair.", cancelTaskMessage: "Cancel the pending GIS task.",
      patchSummary: "Patch pending task: {patch}",
      repairActions: { reproject_layer: "Reproject layer", fix_geometries: "Fix geometries", run_algorithm: "Run processing algorithm", load_vector: "Load vector layer", load_raster: "Load raster layer" },
      riskCategories: {
        crs_risk: "CRS risk", geometry_risk: "Geometry risk", field_risk: "Field risk",
        layer_ambiguity: "Layer ambiguity", output_risk: "Output risk",
        empty_result_risk: "Empty result risk", raster_risk: "Raster risk",
        data_quality_risk: "Data quality risk", runtime_repair_risk: "Runtime repair risk",
      },
    },
    settings: {
      apiBaseUrl: "API Base URL", provider: "Provider",
      providers: { deepseek: "DeepSeek", qwen: "Qwen", glm: "GLM", openaiCompatible: "OpenAI / Compatible" },
      apiKey: "API Key", llmBaseUrl: "LLM Base URL", model: "Model",
      qgisLauncher: "QGIS Launcher", qgisPrefixPath: "QGIS Prefix Path",
      language: "Language", languages: { zh: "Chinese", en: "English" },
      outputDirectory: "Output Directory", chooseDirectory: "Choose directory",
      outputFormat: "Output Format", llmMaxTokens: "Max Output Tokens",
      llmTopP: "Top P", llmJsonMode: "JSON Response Mode",
    },
    statuses: { idle: "Idle", running: "Running", pause_requested: "Pausing", paused: "Paused", cancel_requested: "Cancelling", cancelled: "Cancelled", awaiting_user: "Awaiting user", awaiting_confirmation: "Awaiting confirmation", completed: "Completed", failed: "Failed", checking: "Checking", online: "Online", offline: "Offline", error: "Error" },
    slots: { input_ref: "Input layer", overlay_ref: "Overlay layer", distance: "Distance", input_refs: "Input layers", target_crs: "Target CRS", field: "Field", field_name: "Field name", operator: "Operator", value: "Value", predicate: "Predicate", intersect_ref: "Intersect layer", join_ref: "Join layer", formula: "Formula", x_field: "X field", y_field: "Y field", layer_ref: "Layer", mask_ref: "Mask layer", raster_ref: "Raster layer", output_dir: "Output directory", output_format: "Output format", output_name: "File name" },
  };
}

